### ISSUE TITLE
Suggesting an ignore links feature

### ISSUE THREAD

**Issue by Joy3van** [fluentinstroll/Link-Checker#7]
Hi @fluentinstroll, I think if the app has a feature that allows users to ignore some links, it would enhance the user experience. May I work on this feature?

**Comment by fluentinstroll** [comment]
Absolutely! Please do.

**Comment by Joy3van** [comment]
Hi @fluentinstroll, I have finished the feature, you can find it in my repo under issue-7. Would you like to take a look and review it with git remote?

**Comment by fluentinstroll** [comment]
@Joy3van hey Yifan! I'll take a look at it this evening

**Comment by fluentinstroll** [comment]
@Jot3van Hello again! A lot of things look great, I'm going to add a few things like error handling and I'll change the README to reflect some more use cases. 

If you'd like to look at what I'm changing you can use this sequence of commands:
```
$ git add upstream https://github.com/fluentinstroll/Link-Checker
$ git fetch upstream
$ git checkout -b issue-7-fix upstream/issue-7-fix
```

I'm going to close this issue now, shoot me a message on slack if you'd like to continue discussing this fix :)
